version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    groups:
      aws:
        patterns:
          - "github.com/aws/*"
      charmbracelet:
        patterns:
          - "github.com/charmbracelet/*"
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
