name: CI
on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  test:
    permissions:
      contents: 'read'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'Set up Go'
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: 'Test'
        run: go test -cover ./...
